Repository swyp3-babpool/babpool-backend, pull requests merged in 2024-02, with the labels that each got.

#3 Feature:(response): Add global ApiResponse (#2)
  src/main/java/com/swyp3/babpool/global/common/exception/errorcode/BabpoolErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/exception/errorcode/CustomErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiErrorResponse.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponse.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
Labels: 🛠 Feature, 💻 BackEnd

#4 chore(redis): Add redis in local and test env to store whitelist jwt
  build.gradle
  src/main/java/com/swyp3/babpool/global/util/jwt/JwtTokenizer.java
  src/main/java/com/swyp3/babpool/infra/redis/EmbeddedLocalRedisConfig.java
  src/main/java/com/swyp3/babpool/infra/redis/RedisRepositoryConfig.java
  src/main/java/com/swyp3/babpool/infra/redis/dao/TokenRedisRepository.java
  src/main/java/com/swyp3/babpool/infra/redis/domain/TokenForRedis.java
  src/test/java/com/swyp3/babpool/infra/redis/dao/TokenRedisRepositoryTest.java
Labels: 🔗 Chore, 💻 Infra, 💻 BackEnd

#8 Feature: Get user info from Kakao
  build.gradle
  src/main/java/com/swyp3/babpool/global/config/FeignClientConfig.java
  src/main/java/com/swyp3/babpool/infra/auth/AuthJwtParser.java
  src/main/java/com/swyp3/babpool/infra/auth/AuthPlatform.java
  src/main/java/com/swyp3/babpool/infra/auth/BabpoolPublicKey.java
  src/main/java/com/swyp3/babpool/infra/auth/ClientIp.java
  src/main/java/com/swyp3/babpool/infra/auth/PlatformDeserializer.java
  src/main/java/com/swyp3/babpool/infra/auth/PublicKeyGenerator.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoClient.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoMemberProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoPlatformMemberResponse.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoPublicKeys.java
  src/test/java/com/swyp3/babpool/infra/auth/KakaoClientTest.java
Labels: 🛠 Feature, 💻 BackEnd

#11 feat(auth): Add social login logic
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/domain/user/domain/User.java
  src/main/java/com/swyp3/babpool/domain/user/domain/UserRole.java
  src/main/java/com/swyp3/babpool/domain/user/domain/UserStatus.java
  src/main/java/com/swyp3/babpool/infra/auth/AuthJwtParser.java
  src/main/java/com/swyp3/babpool/infra/auth/PublicKeyGenerator.java
  src/main/java/com/swyp3/babpool/infra/auth/controller/AuthController.java
  src/main/java/com/swyp3/babpool/infra/auth/dao/AuthRepository.java
  src/main/java/com/swyp3/babpool/infra/auth/domain/Auth.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoMemberProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoPublicKeys.java
  src/main/java/com/swyp3/babpool/infra/auth/request/LoginRequestDTO.java
  src/main/java/com/swyp3/babpool/infra/auth/response/AuthMemberResponse.java
  src/main/java/com/swyp3/babpool/infra/auth/response/LoginResponseDTO.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
  src/main/resources/mapper/AuthMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#12 refactor(redis): Delete redis pwd setting code as comment
  .github/babpool_pull_request_template.md
  src/main/java/com/swyp3/babpool/infra/redis/RedisRepositoryConfig.java
Labels: 💻 BackEnd, ♻ Refactoring

#15 feat(uuid): Add uuid process (#7)
  build.gradle
  src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
  src/main/java/com/swyp3/babpool/global/util/jwt/JwtAuthenticator.java
  src/main/java/com/swyp3/babpool/global/util/jwt/JwtTokenInterceptor.java
  src/main/java/com/swyp3/babpool/global/uuid/application/UuidService.java
  src/main/java/com/swyp3/babpool/global/uuid/application/UuidServiceV7.java
  src/main/java/com/swyp3/babpool/global/uuid/dao/UserUuidRepository.java
  src/main/java/com/swyp3/babpool/global/uuid/domain/UserUuid.java
  src/main/java/com/swyp3/babpool/global/uuid/util/UuidResolver.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/main/resources/mapper/UserUuidMapper.xml
  src/test/java/com/swyp3/babpool/global/util/jwt/JwtAuthenticatorTest.java
  src/test/java/com/swyp3/babpool/global/uuid/application/UuidResolverTest.java
  src/test/java/com/swyp3/babpool/global/uuid/application/UuidServiceV7Test.java
Labels: 🛠 Feature, 💻 BackEnd

#16 feat(profile): Add overall structure of the profile domain
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileListRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileUpdateResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/Profile.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/ProfileException.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/handler/ProfileExceptionHandler.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd
