Repository swyp3-babpool/babpool-backend, pull requests merged in 2024-03, with the labels that each got.

#19 feat(s3): Add s3 image upload and delete feature
  build.gradle
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckS3Api.java
  src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java
  src/main/java/com/swyp3/babpool/infra/s3/config/S3Config.java
  src/main/java/com/swyp3/babpool/infra/s3/exception/AwsS3ErrorCode.java
  src/main/java/com/swyp3/babpool/infra/s3/exception/AwsS3Exception.java
  src/main/java/com/swyp3/babpool/infra/s3/exception/AwsS3ExceptionHandler.java
  src/test/java/com/swyp3/babpool/infra/s3/application/AwsS3ProviderTest.java
Labels: 🛠 Feature, 💻 BackEnd

#20 refactor(cookie): Update ApiResponseWithCookie to set domain and expi…
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
Labels: 💻 BackEnd, ♻ Refactoring

#21 rename(github): Update pr template file name
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✏️ Documentation

#22 feat(uuid): Add getUuidByUserId method in UuidService
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/swyp3/babpool/global/uuid/application/UuidServiceV7.java
  src/main/java/com/swyp3/babpool/global/uuid/dao/UserUuidRepository.java
  src/main/resources/mapper/UserUuidMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#23 feat(auth): Add social login process
  src/main/java/com/swyp3/babpool/global/common/exception/errorcode/BabpoolErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/exception/handler/BaseExceptionHandler.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
  src/main/java/com/swyp3/babpool/global/uuid/application/UuidService.java
  src/main/java/com/swyp3/babpool/infra/auth/AuthJwtParser.java
  src/main/java/com/swyp3/babpool/infra/auth/ClientIp.java
  src/main/java/com/swyp3/babpool/infra/auth/PublicKeyGenerator.java
  src/main/java/com/swyp3/babpool/infra/auth/controller/AuthController.java
  src/main/java/com/swyp3/babpool/infra/auth/exception/AuthException.java
  src/main/java/com/swyp3/babpool/infra/auth/exception/errorcode/AuthExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/infra/auth/exception/handler/AuthExceptionHandler.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoMemberProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoPublicKeys.java
  src/main/java/com/swyp3/babpool/infra/auth/request/LoginRequestDTO.java
  src/main/java/com/swyp3/babpool/infra/auth/response/AuthMemberResponse.java
  src/main/java/com/swyp3/babpool/infra/auth/response/LoginResponseWithRefreshToken.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
Labels: 🛠 Feature, 💻 BackEnd

#24 feat(jwt): Add api and resolve response cookie error
  src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
  src/main/java/com/swyp3/babpool/global/common/response/config/ApiResponseConfigProperties.java
  src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtAuthenticator.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtTokenInterceptor.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtTokenizer.java
  src/main/java/com/swyp3/babpool/global/jwt/api/JwtApiPermitted.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtService.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
  src/main/java/com/swyp3/babpool/global/jwt/application/response/JwtPairDto.java
  src/main/java/com/swyp3/babpool/global/jwt/exception/BabpoolJwtException.java
  src/main/java/com/swyp3/babpool/global/jwt/exception/BadCredentialsException.java
  src/main/java/com/swyp3/babpool/global/jwt/exception/errorcode/JwtExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/global/jwt/exception/handler/JwtExceptionHandler.java
  src/main/java/com/swyp3/babpool/global/uuid/exception/UuidException.java
  src/main/java/com/swyp3/babpool/global/uuid/exception/UuidExceptionHandler.java
  src/main/java/com/swyp3/babpool/infra/auth/exception/handler/AuthExceptionHandler.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/test/java/com/swyp3/babpool/global/util/jwt/JwtAuthenticatorTest.java
  src/test/java/com/swyp3/babpool/global/util/jwt/JwtTokenizerTest.java
  src/test/java/com/swyp3/babpool/global/util/jwt/application/JwtServiceImplTest.java
Labels: 🛠 Feature, 💻 BackEnd, ♻ Refactoring

#25 fix: response jwt and add exception
  src/main/java/com/swyp3/babpool/infra/auth/AuthJwtParser.java
  src/main/java/com/swyp3/babpool/infra/auth/response/AuthMemberResponse.java
Labels: 💻 BackEnd

#27 fix(auth): Get token from kakao
  src/main/java/com/swyp3/babpool/infra/auth/exception/errorcode/AuthExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoTokenProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/request/LoginRequestDTO.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
Labels: 🛠 Feature, 💻 BackEnd

#30 chore(workflow): Update github actions workflow
  .github/workflows/github-actions-server.yaml
Labels: 🔗 Chore, 💻 BackEnd

#32 fix(cors): Update CorsConfig from string array to several string vali…
  src/main/java/com/swyp3/babpool/global/config/CorsConfig.java
Labels: 🚨 Bug, 💻 BackEnd

#33 Develop merge into main
  src/main/java/com/swyp3/babpool/global/config/CorsConfig.java
Labels: 🚀 Release

#29 feat(profile): Add profile list paging #28
  build.gradle
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileListRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfilePagingConditions.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/request/PagingRequestList.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 🔗 Chore, 💻 BackEnd

#34 release: Merge develop into main for apply profile features
  build.gradle
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileListRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfilePagingConditions.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/request/PagingRequestList.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🚀 Release

#38 feat(uuid): Add getUserIdByUuid method in uuid service
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/global/uuid/application/UuidService.java
  src/main/java/com/swyp3/babpool/global/uuid/application/UuidServiceV7.java
Labels: 🛠 Feature, 💻 BackEnd

#39 feat(profile): Add paging sort type recent profile modify date as default
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/config/PagingSortTypeMappingConfig.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd, ♻ Refactoring

#41 fix(uuid): Update uui repository add param annotation to specifiy parameter
  src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
  src/main/java/com/swyp3/babpool/global/uuid/dao/UserUuidRepository.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/test/java/com/swyp3/babpool/global/uuid/application/UuidServiceV7Test.java
Labels: 🚨 Bug, 💻 BackEnd, ♻ Refactoring

#44 refactor(profile): Update profile paging response (#40)
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfilePermitApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingDto.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd, ♻ Refactoring

#42 feature: add user sign up api
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserService.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/requset/LoginRequestDTO.java
  src/main/java/com/swyp3/babpool/domain/user/application/requset/SignUpRequestDTO.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/LoginResponseDTO.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/LoginResponseWithRefreshToken.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/domain/user/exception/SignUpException.java
  src/main/java/com/swyp3/babpool/domain/user/exception/errorcode/SignUpExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/domain/user/exception/handler/SignUpExceptionHandler.java
  src/main/java/com/swyp3/babpool/infra/auth/controller/AuthController.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
  src/main/resources/mapper/ProfileMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#47 feat: Add get profile data api
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailDaoDto.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/api/requset/LoginRequestDTO.java
  src/main/java/com/swyp3/babpool/domain/user/api/requset/SignUpRequestDTO.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserService.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDaoDto.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/global/config/CorsConfig.java
  src/main/resources/mapper/ProfileMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#49 feat(appointment): Add appointment features
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentCreateResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentReceiveResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentSendResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
  src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketHandler.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/Appointment.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRequestMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/AppointmentException.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/handler/AppointmentExceptionHandler.java
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckStompAPi.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#55 feat(review, appointment): Add features to resolve #51, appointment history
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentHistoryDoneResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentHistoryRefuseResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/config/PagingSortTypeMappingConfig.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java
  src/main/java/com/swyp3/babpool/domain/review/api/ReviewApi.java
  src/main/java/com/swyp3/babpool/domain/review/api/request/ReviewCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/review/api/request/ReviewUpdateRequest.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewService.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewCountByTypeResponse.java
  src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewPagingResponse.java
  src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewSaveResponse.java
  src/main/java/com/swyp3/babpool/domain/review/dao/ReviewRepository.java
  src/main/java/com/swyp3/babpool/domain/review/domain/Review.java
  src/main/java/com/swyp3/babpool/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/swyp3/babpool/domain/review/exception/ReviewException.java
  src/main/java/com/swyp3/babpool/domain/review/exception/ReviewExceptionHandler.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/ReviewMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#53 fix(profile): fix keywords response
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/KeywordsResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailDaoDto.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDaoDto.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#56 feat: add profile update
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileUpdateResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/PossibleDate.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#58 feat(appointment): Add get specific profile's possible appointment da…
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentPossibleDateTimeResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#59 feat: get profile update default date
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultDaoDto.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#66 refactor(review): Resolve review paging error and update several codes
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/review/api/ReviewApi.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewService.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewInfoResponse.java
  src/main/java/com/swyp3/babpool/domain/review/dao/ReviewRepository.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/ReviewMapper.xml
Labels: 🛠 Feature, 💻 BackEnd, ♻ Refactoring

#67 fix: Fix class and method name
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileKeywordsResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileDefault.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileDetail.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 💻 BackEnd

#68 feat: add review and appointment history data
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
Labels: 🛠 Feature, 💻 BackEnd

#70 refactor: Update profile and appoinment that isn't working correctly
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentPossibleDateTimeResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtTokenInterceptor.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/ProfileMapper.xml
Labels: 💻 BackEnd, ♻ Refactoring

#71 release: Merge develop into main for apply fixed errors
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentPossibleDateTimeResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDefaultResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileKeywordsResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileDefault.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileDetail.java
  src/main/java/com/swyp3/babpool/domain/review/api/ReviewApi.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewService.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/review/application/response/ReviewInfoResponse.java
  src/main/java/com/swyp3/babpool/domain/review/dao/ReviewRepository.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtTokenInterceptor.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/ProfileMapper.xml
  src/main/resources/mapper/ReviewMapper.xml
Labels: 🚀 Release, 💻 BackEnd

#75 refactor(profile, signout): Update profile list response field, Update signout response, Update profile image update logic
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
  src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java
Labels: 💻 BackEnd, ♻ Refactoring

#73 Feat: refuse appointment
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentRefuseRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRefuseResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRefuseMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#76 feat(scheduler): Add scheduler for appointment status to expire automatically
  src/main/java/com/swyp3/babpool/BabpoolApplication.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/global/config/AppointmentSchedulerConfig.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#79 fix(appointment): Resolve mybatis foreach grammer in appointment mapper
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🚨 Bug, 💻 BackEnd

#80 release: Merge develop branch into main, apply refactoring and bug fix
  src/main/java/com/swyp3/babpool/BabpoolApplication.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentRefuseRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentHistoryRefuseResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRefuseResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRefuseMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/eoorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfilePagingResponse.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/global/config/AppointmentSchedulerConfig.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
  src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🚀 Release

#82 Release: Merge develop branch into main branch to apply update profile list select query
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🚀 Release

#83 feat: Accept appointment api
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentAcceptRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentRejectRequest.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentAcceptResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRejectResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentAcceptMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRejectMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/AppointmentException.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#85 refactor(appointment): Update findAppointmentPossibleDateTimeByProfil… query
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ♻ Refactoring

#86 fix(user): add @Transactional
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🚨 Bug, 💻 BackEnd

#87 Feat : get user grade api
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserService.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/UserGradeResponse.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#89 Feat/get appointment data
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRequesterPossibleDateTimeResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#91 feat: Add get profile active flag api
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileRegistrationResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#95 fix: change ProfileUpdateRequest keywords data type
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
Labels: 🚨 Bug, 💻 BackEnd

#97 fix(conflict): Already up to date
  .github/workflows/github-actions-server.yaml
Labels: 🔗 Chore

#96 release: Merge develop branch into main
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentHistoryRefuseResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRequesterPossibleDateTimeResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRejectMessage.java
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/api/request/ProfileUpdateRequest.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileRegistrationResponse.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🚀 Release

#98 feat: Add sign out and sign down
  .github/workflows/github-actions-server.yaml
  build.gradle
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserService.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/dao/ExitInfoRepository.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/domain/user/domain/UserStatus.java
  src/main/java/com/swyp3/babpool/domain/user/exception/SignDownException.java
  src/main/java/com/swyp3/babpool/domain/user/exception/errorcode/SignDownExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/response/CookieProvider.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtAuthenticator.java
  src/main/java/com/swyp3/babpool/infra/auth/dao/AuthRepository.java
  src/main/java/com/swyp3/babpool/infra/auth/exception/errorcode/AuthExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoMemberProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/main/resources/mapper/AuthMapper.xml
  src/main/resources/mapper/ExitInfoMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#99 release: Merge develop into main, apply sign out, sign down, cookie
  build.gradle
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserSignOutApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserService.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/dao/ExitInfoRepository.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/domain/user/domain/UserStatus.java
  src/main/java/com/swyp3/babpool/domain/user/exception/SignDownException.java
  src/main/java/com/swyp3/babpool/domain/user/exception/errorcode/SignDownExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/global/common/response/CookieProvider.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtAuthenticator.java
  src/main/java/com/swyp3/babpool/infra/auth/dao/AuthRepository.java
  src/main/java/com/swyp3/babpool/infra/auth/exception/errorcode/AuthExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoMemberProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/kakao/KakaoProvider.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/main/resources/mapper/AuthMapper.xml
  src/main/resources/mapper/ExitInfoMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🚀 Release

#101 refactor(profile): Update return true when image is not requested to server
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
Labels: 💻 BackEnd, ♻ Refactoring

#102 feat(handler): Update validation exception handler
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/api/request/AppointmentCreateRequest.java
  src/main/java/com/swyp3/babpool/global/common/exception/handler/BaseExceptionHandler.java
  src/main/java/com/swyp3/babpool/global/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiErrorResponse.java
  src/test/java/com/swyp3/babpool/domain/appointment/api/AppointmentApiTest.java
Labels: 🛠 Feature, 💻 BackEnd, ♻ Refactoring

#106 refactor: Resolve #94 #100 #104
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/global/common/exception/handler/BaseExceptionHandler.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
  src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java
  src/test/java/com/swyp3/babpool/domain/appointment/api/AppointmentApiMockMvcTest.java
  src/test/java/com/swyp3/babpool/domain/appointment/api/AppointmentApiTest.java
  src/test/java/com/swyp3/babpool/infra/s3/application/AwsS3ProviderTest.java
Labels: 💻 BackEnd, ♻ Refactoring, ✔Fix

#108 feat(appointment): Add cancel appointment by request which not accept yet
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentCancelResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🛠 Feature, 💻 BackEnd

#111 Fix: get appointment detail
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentAcceptDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentReceiveWaitingDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentSendWaitingDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/LoginResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/LoginResponseWithRefreshToken.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDto.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/main/resources/mapper/UserMapper.xml
Labels: 💻 BackEnd, ✔Fix

#113 release: Merge develop into main, apply
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentAcceptResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentCancelResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentAcceptDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentReceiveWaitingDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentSendWaitingDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/LoginResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/LoginResponseWithRefreshToken.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageResponse.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDto.java
  src/main/java/com/swyp3/babpool/domain/user/dao/UserRepository.java
  src/main/java/com/swyp3/babpool/global/common/exception/handler/BaseExceptionHandler.java
  src/main/java/com/swyp3/babpool/global/common/response/ApiResponseWithCookie.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
  src/main/java/com/swyp3/babpool/infra/s3/application/AwsS3Provider.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/test/java/com/swyp3/babpool/domain/appointment/api/AppointmentApiMockMvcTest.java
  src/test/java/com/swyp3/babpool/infra/s3/application/AwsS3ProviderTest.java
Labels: 🚀 Release

#118 Fix: login logic for exit user
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/domain/User.java
  src/main/java/com/swyp3/babpool/domain/user/domain/UserStatus.java
  src/main/resources/mapper/UserMapper.xml
Labels: 💻 BackEnd, ✔Fix

#120 feat(profile): Add active flag update query in profileMaper
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/user/api/UserApi.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🛠 Feature, 💻 BackEnd, ✔Fix

#123 fix: signdown issue, update possible date and time issue
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/dao/ProfileRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/PossibleDateAndTime.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/exception/errorcode/SignDownExceptionErrorCode.java
  src/main/java/com/swyp3/babpool/infra/auth/dao/AuthRepository.java
  src/main/java/com/swyp3/babpool/infra/auth/service/AuthService.java
  src/main/resources/mapper/AuthMapper.xml
  src/main/resources/mapper/PossibleDateTimeMapper.xml
  src/test/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImplTest.java
Labels: 💻 BackEnd, ✔Fix

#124 fix(mapper): Update profileDateTimeMapper alias
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/PossibleDateAndTime.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/PossibleDateTimeMapper.xml
  src/test/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImplTest.java
Labels: 💻 BackEnd, ♻ Refactoring, ✔Fix

#127 Fix: accept appointment api & get detail accept appointemtn api response
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentAcceptResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentAcceptDetailResponse.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#129 Fix/response
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentAcceptResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/appointmentdetail/AppointmentAcceptDetailResponse.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#131 refactor: updatePossibleDateTime, profileDetailResponse
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
  src/main/java/com/swyp3/babpool/domain/profile/api/ProfileApi.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/response/ProfileDetailResponse.java
  src/main/resources/mapper/PossibleDateTimeMapper.xml
Labels: 🛠 Feature, 💻 BackEnd, ♻ Refactoring

#132 Fix/update profile
  src/main/java/com/swyp3/babpool/domain/possibledatetime/dao/PossibleDateTimeRepository.java
  src/main/java/com/swyp3/babpool/domain/possibledatetime/domain/PossibleDateInsertDto.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/resources/mapper/PossibleDateTimeMapper.xml
Labels: 💻 BackEnd, ✔Fix

#135 Hotfix/pro hyundo
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#136 release: Merge develop into main, to apply hotfix
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🚀 Release

#138 fix: query
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#139 Hotfix/pro hyundo
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🚀 Release, 💻 BackEnd, ✔Fix

#142 release: Merge hotfix/proHyundo into main
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileService.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/exception/errorcode/ProfileErrorCode.java
  src/main/java/com/swyp3/babpool/domain/user/application/UserServiceImpl.java
  src/main/java/com/swyp3/babpool/global/config/WebMvcInterceptJwtConfig.java
  src/main/java/com/swyp3/babpool/global/jwt/JwtTokenizer.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtService.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckApi.java
Labels: 🚀 Release

#144 fix: refused history and appointment list orderby
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#145 release: Merge develop into main
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/global/config/AppointmentSchedulerConfig.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🚀 Release

#146 Hotfix/appointment
  .github/workflows/github-actions-server.yaml
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#147 Fix: 밥약 상세 조회 시 상대방 데이터가 보이도록 수정
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#148 Hotfix/review: 리뷰 생성 시 appointment_status 값 변경
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/review/api/request/ReviewCreateRequest.java
  src/main/java/com/swyp3/babpool/domain/review/application/ReviewServiceImpl.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#150 Feat/get reject reason
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRefuseDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 💻 BackEnd, ✔Fix

#151 cors: Update set allowed origins for websocket add jxy.me
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
Labels: 💻 BackEnd, ♻ Refactoring

#152 release: Merge develop into main
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/api/AppointmentApi.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentService.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/application/response/AppointmentRefuseDetailResponse.java
  src/main/java/com/swyp3/babpool/domain/appointment/config/AppointmentWebSocketConfig.java
  src/main/java/com/swyp3/babpool/domain/appointment/dao/AppointmentRepository.java
  src/main/java/com/swyp3/babpool/domain/appointment/exception/errorcode/AppointmentErrorCode.java
  src/main/resources/mapper/AppointmentMapper.xml
Labels: 🚀 Release

#153 release: Merge develop into main, to apply convertandsend to useruuid instead profileid
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckStompAPi.java
Labels: 🚀 Release

#154 refactor(appointment): Update appointment real-time message body
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentAcceptMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRejectMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRequestMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentSocketMessageType.java
  src/main/java/com/swyp3/babpool/domain/profile/application/ProfileServiceImpl.java
  src/main/java/com/swyp3/babpool/global/jwt/application/JwtServiceImpl.java
  src/main/java/com/swyp3/babpool/infra/health/api/HealthCheckStompAPi.java
Labels: 💻 BackEnd, ♻ Refactoring

#156 Develop
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentAcceptMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRejectMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentRequestMessage.java
  src/main/java/com/swyp3/babpool/domain/appointment/domain/AppointmentSocketMessageType.java
  src/main/resources/mapper/AppointmentMapper.xml
  src/main/resources/mapper/ProfileMapper.xml
Labels: 🚀 Release

#157 HOTFIX(appointment): Update getAppointmentDetail response set contact…
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDto.java
Labels: 🚀 Release, 💻 BackEnd, ✔Fix

#159 fix(profile): Update typo error in profile paging sort type
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/appointment/application/AppointmentServiceImpl.java
  src/main/java/com/swyp3/babpool/domain/profile/config/PagingSortTypeMappingConfig.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java
  src/main/java/com/swyp3/babpool/domain/user/application/response/MyPageUserDto.java
Labels: 💻 BackEnd, ✔Fix

#160 HOTFIX: 쿠키가 존재하지 않는 경우에도 401 응답
  .github/workflows/github-actions-server.yaml
  src/main/java/com/swyp3/babpool/domain/profile/config/PagingSortTypeMappingConfig.java
  src/main/java/com/swyp3/babpool/domain/profile/domain/ProfileSortType.java
  src/main/java/com/swyp3/babpool/global/jwt/api/JwtApiPermitted.java
Labels: 🚀 Release, 💻 BackEnd, ✔Fix
